name: Sync hash.json files

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download only hash.json
        run: |
          git clone --depth 1 --filter=blob:none --sparse https://github.com/leotorrez/ZZ-Model-Importer-Assets.git upstream
          cd upstream
          git sparse-checkout set '**/hash.json'
          cd ..

          rm -rf hashes
          mkdir hashes
          cp -r upstream/* hashes/

      - name: Commit update
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add hashes

          git commit -m "Update hash files" || exit 0
          git push
